Abort configure when include/config.h.in is missing

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -5,7 +5,7 @@ dnl  Copyright (C) 1999 Hugh Blemings & Pavel Janík ml.
 dnl                2000 Karel Zak, Pawe³ Kot
 dnl                2002 BORBELY Zoltan
 dnl
-dnl  $Id: configure.in,v 1.75 2002-04-23 09:44:35 pkot Exp $
+dnl  $Id: configure.in,v 1.76 2002-04-30 21:00:51 bozo Exp $
 dnl
 
 AC_INIT(gnokii/gnokii.c)
@@ -18,6 +18,19 @@ AC_PREFIX_DEFAULT("/usr/local")
 dnl ======================== Default setting
 CFLAGS="-O2 -Wall"
 ALL_LINGUAS="cs de et fi nl sk pl it sl"
+
+dnl ======================== Check for include/config.h.in
+AC_MSG_CHECKING([for include/config.h.in])
+if test -f include/config.h.in; then
+	AC_MSG_RESULT(yes)
+else
+	AC_MSG_RESULT(no)
+	echo '*************************************************'
+	echo 'include/config.h.in missing, run autoheader first'
+	echo 'autoheader is part of the autoconf package'
+	echo '*************************************************'
+	exit 1
+fi
 
 dnl ======================== Checks for programs.
 AC_PROG_CC
